import os


class Config(object):
    SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URI')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SECRET_KEY = os.getenv('SECRET_KEY')
    SHORT_URL_LENGTH = 6
    MIN_URL_LENGTH = 1
    MAX_URL_LENGTH = 256
    MIN_CUSTOM_ID_LENGTH = 1
    MAX_CUSTOM_ID_LENGTH = 16
    CUSTOM_ID_PATTERN = r'^[a-zA-Z0-9]+$'
    